import { CategoryCardProps } from '@/shared/ui/CategoryCard/type'

export const CATEGORIES: CategoryCardProps[] = [
  {
    title: 'Электроника',
    slug: 'electronics',
    image: '/images/categories/electronics.svg',
    href: '/catalog?categorySlug=electronics',
    colSpan: 5,
    rowSpan: 1,
    imagePosition: 'top-left',
    titlePosition: 'center-right',
  },

  {
    title: 'Детские товары',
    slug: 'childrenGoods',
    image: '/images/categories/children-goods.svg',
    href: '/catalog?categorySlug=childrenGoods',
    colSpan: 5,
    rowSpan: 1,
    imagePosition: 'bottom-right',
    titlePosition: 'left',
    customStyles: {
      paddingRight: '50px',
    },
  },
  {
    title: 'Медицинское оборудование для реабилитации',
    slug: 'medicalEquipment',
    image: '/images/categories/medical-equipment.svg',
    href: '/catalog?categorySlug=medicalEquipment',
    colSpan: 5,
    rowSpan: 2,
    imagePosition: 'bottom-right',
    titlePosition: 'left',
  },
  {
    title: 'Спорт и активный отдых',
    slug: 'sport',
    image: '/images/categories/sport.svg',
    href: '/catalog?categorySlug=sport',
    colSpan: 6,
    rowSpan: 1,
    imagePosition: 'bottom-right',
    titlePosition: 'left',
  },
  {
    title: 'Одежда и аксессуары',
    slug: 'clothes',
    image: '/images/categories/clothes.svg',
    href: '/catalog?categorySlug=clothes',
    colSpan: 6,
    rowSpan: 1,
    imagePosition: 'top-left',
    titlePosition: 'left',
    customStyles: {
      paddingLeft: '127px',
    },
  },
  {
    title: 'Хобби и творчество',
    slug: 'hobbies',
    image: '/images/categories/hobbies.svg',
    href: '/catalog?categorySlug=hobbies',
    colSpan: 5,
    rowSpan: 2,
    imagePosition: 'bottom-right',
    titlePosition: 'left',
  },
  {
    title: 'Строительные инструменты и техника',
    slug: 'tools',
    image: '/images/categories/tools.svg',
    subcategories: [
      'Электроинструменты',
      'Ручной инструмент',
      'Строительное оборудование',
      'Садовая техника ',
    ],
    href: '/catalog?categorySlug=tools',
    colSpan: 10,
    rowSpan: 1,
    imagePosition: 'top-left',
    titlePosition: 'center-right',
    customStyles: {
      paddingLeft: '121px',
    },
  },
  {
    title: 'Праздники и мероприятия',
    slug: 'events',
    image: '/images/categories/events.svg',
    href: '/catalog?categorySlug=events',
    colSpan: 6,
    rowSpan: 1,
    imagePosition: 'bottom-right',
    titlePosition: 'left',
  },

  {
    title: 'Музыкальное оборудование',
    slug: 'musicalEquipment',
    image: '/images/categories/musical-equipment.svg',
    href: '/catalog?categorySlug=musicalEquipment',
    colSpan: 6,
    rowSpan: 1,
    imagePosition: 'bottom-right',
    titlePosition: 'left',
  },
]
