import type { Metadata } from 'next'
import localFont from 'next/font/local'
import '@/shared/styles/globals.css'
import { Providers } from './providers'

const HelveticaNeue = localFont({
  src: [
    {
      path: '../../public/fonts/HelveticaNeue/HelveticaNeue-Thin.otf',
      weight: '200',
      style: 'normal',
    },
    {
      path: '../../public/fonts/HelveticaNeue/HelveticaNeue-Light.otf',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../../public/fonts/HelveticaNeue/HelveticaNeue-Roman.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/fonts/HelveticaNeue/HelveticaNeue-Medium.otf',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../../public/fonts/HelveticaNeue/HelveticaNeue-Bold.otf',
      weight: '700',
      style: 'normal',
    },
  ],
  display: 'swap',
  variable: '--font-helvetica-neue',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`flex h-screen w-full flex-col antialiased ${HelveticaNeue.variable} items-center`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
